#spring:
#  application:
#    name: ProductService
#  datasource:
#    url: jdbc:mysql://localhost:3306/product_db
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update

spring:
  application:
    name: ProductService

  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=youraccount;AccountKey=yourkey;EndpointSuffix=core.windows.net

