#spring:
#  application:
#    name: ProductService
#  datasource:
#    url: jdbc:mysql://localhost:3306/product_db
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update


spring:
  application:
    name: ProductService

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

azure:
  storage:
    account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
    account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
    blob-container-name: ${AZURE_STORAGE_BLOB_CONTAINER_NAME}
    archive-container-name: ${AZURE_STORAGE_ARCHIVE_CONTAINER_NAME}
